/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 mari.glb --transform
*/
import React, { useRef, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import utils from './utils'
import { useLoader } from '@react-three/fiber'
import { TextureLoader } from 'three/src/loaders/TextureLoader'
import { sRGBEncoding } from 'three'

export function Mari(props) {
    const group = useRef()
    const { nodes, materials, animations } = useGLTF('/mari-transformed.glb')
    //setting animations
    const { actions,mixer} = useAnimations(animations, group)
    const clips = [actions.dashmari,actions.fallingmari,actions.idlemari,actions.runmari,actions.sprintmari,actions.stopmari,actions.tpose];
    const animNames = ['dash','fall','idle','run','sprint','run stop','neutral']
    //setting up the material/ textures TODO SETUP THIS IN UTILS!
    const [capeTexture,clothingTexture,eyeTexture,faceTexture] = useLoader(
        TextureLoader,
        [
            'textures/huntress-cape.png',
            'textures/huntress-clothing.png',
            'textures/huntress-eye.png',
            'textures/huntress-face.png',
        ]
    )
    clothingTexture.flipY = false
    faceTexture.flipY = false
    capeTexture.flipY = false
    eyeTexture.flipY = false
    clothingTexture.encoding = sRGBEncoding
    faceTexture.encoding = sRGBEncoding
    capeTexture.encoding = sRGBEncoding
    eyeTexture.encoding = sRGBEncoding
    //setting the GUI
    utils(clips,animNames,mixer);
    //setting up the model itself
    return (
        
        <mesh >
            
            <group ref={group} {...props} dispose={null}>
                <group name="Scene">
                    <group name="mari_gamerig">
                        <primitive object={nodes['DEF-spine']} />

                        <skinnedMesh
                            name="Hood"
                            geometry={nodes.Hood.geometry}
                            material={materials.CAPE}
                            skeleton={nodes.Hood.skeleton}
                        />
                        <skinnedMesh
                            name="Main"
                            geometry={nodes.Main.geometry}
                            material={materials.MAIN}
                            skeleton={nodes.Main.skeleton}
                        />
                        <skinnedMesh
                            name="Eyes"
                            geometry={nodes.Eyes.geometry}
                            material={materials.EYES}
                            skeleton={nodes.Eyes.skeleton}
                            morphTargetDictionary={
                                nodes.Eyes.morphTargetDictionary
                            }
                            morphTargetInfluences={
                                nodes.Eyes.morphTargetInfluences
                            }
                        />
                        <skinnedMesh
                            name="Head"
                            geometry={nodes.Head.geometry}
                            material={materials.FACE}
                            skeleton={nodes.Head.skeleton}
                            morphTargetDictionary={
                                nodes.Head.morphTargetDictionary
                            }
                            morphTargetInfluences={
                                nodes.Head.morphTargetInfluences
                            }
                        />
                    </group>
                </group>
            </group>
            
        </mesh>
    )
}

useGLTF.preload('/mari-transformed.glb')
